const VERIFY_REQUEST = "VERIFY_REQUEST";
const VERIFY_SUCCESS = "VERIFY_SUCCESS";
const VERIFY_FAILURE = "VERIFY_FAILURE";

export default {
    VERIFY_REQUEST,
    VERIFY_SUCCESS,
    VERIFY_FAILURE    
};